dist: trusty
sudo: false
language: php

php:
  - 7.3
  - 7.4snapshot

before_install:
  - travis_retry composer self-update

install:
  - composer install

jobs:
  include:
    - stage: Code Quality
      env: phpcs
      script:
        - ./vendor/bin/phpcs

    - stage: Code Quality
      env: phpstan
      script:
        - ./vendor/bin/phpstan analyze

    - stage: Code Quality
      env: infection
      script:
        - ./vendor/bin/infection --min-msi=99

cache:
  directories:
    - $HOME/.composer/cache
