dist: trusty
sudo: false
language: php

php:
  - 7.3
  - 7.4snapshot

before_install:
  - travis_retry composer self-update

install:
  - composer install

jobs:
  include:
    - stage: Test
      env: coverage
      script:
        - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
      after_script:
        - travis_retry wget https://scrutinizer-ci.com/ocular.phar
        - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Code Quality
      env: phpcs
      script:
        - ./vendor/bin/phpcs

    - stage: Code Quality
      env: phpstan
      script:
        - ./vendor/bin/phpstan analyze

    - stage: Code Quality
      env: infection
      script:
        - ./vendor/bin/infection --min-msi=99

cache:
  directories:
    - $HOME/.composer/cache
